### ISSUE TITLE
里面的支付maven依赖找不到

### ISSUE THREAD

**Issue by ZuulAndRibbon** [mengday/springboot-pay-example#1]
现在在maven中央库只能找到：
```xml
<dependency>
<groupId>com.alipay.sdk</groupId>
<artifactId>alipay-sdk-java</artifactId>
<version>3.7.4.ALL</version>
</dependency>
```
alipay-trade-sdk是什么的，只能找到alipay-sdk-java

**Comment by chenyeshen** [comment]
创建lib  maven 本地加入

**Comment by chenyeshen** [comment]
> 现在在maven中央库只能找到：
> 
> ```
> <dependency>
> <groupId>com.alipay.sdk</groupId>
> <artifactId>alipay-sdk-java</artifactId>
> <version>3.7.4.ALL</version>
> </dependency>
> ```
> 
> alipay-trade-sdk是什么的，只能找到alipay-sdk-java

创建lib maven 本地加入

**Comment by mengday** [comment]
README.md中列举的博客中"支付宝集成-准备工作"这篇博文的最下方说明了获取jar的方式
